# Generated by Django 5.0.6 on 2024-11-29 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('author', models.TextField(default=None)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('total_pages', models.IntegerField()),
                ('cover', models.ImageField(blank=True, default='', upload_to='books/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('categories', models.ManyToManyField(related_name='books', to='books.category')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
